application: jikokunohi
version: 4
runtime: python
api_version: 1

default_expiration: "7d 5h"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 1d

- url: /css
  static_dir: static/css
  expiration: 1d

- url: /img
  static_dir: static/img
  expiration: 1d

- url: /js
  static_dir: static/js
  expiration: 4h

- url: /.*
  script: dudlr/app.py
